### ISSUE TITLE
RIMMF: Why doesn't RIMMF create brief PFC records when importing Bib, if no NAF data can be found?

### ISSUE THREAD

**Issue by GordonDunsire** [RDARegistry/rballs#4]
RIMMF does not create a brief placeholder record for a Person, Family, or Corporate Body (PFC) when it imports a MARC21 Bibliographic record but no LC Name Authority File data can be found.  Surely it would be better to create such records during import, rather than after import.

**Comment by tmqrichard** [comment]
Gordon

We have talked about this over the years, and lately, decided there's just no reason to not do this. 
(Thanks for the prompting)

Therefore, in more recent versions of RIMMF (after Release 150502) you will find this capability listed on the 'Data options' form:
"During import, manufacture entity records for Agents without authority"

It will be enabled by default.
